version: '3'

services:

  selenium:
    image: selenium/standalone-chrome:3.141.59-titanium
    volumes:
      - "/dev/shm:/dev/shm"

  robot:
    build: .
    depends_on:
      - selenium
    environment:
      SELENIUM_URL: "http://selenium:4444/wd/hub"
